Pull Request pour Review par Bastien
uclouvain/formation-metier pull request #23
Opened 2022-11-18 15:09 UTC by vbrichant

2022-11-29 09:38 UTC, basmot requested changes

2022-11-29 09:38 UTC, basmot commented on formation_metier/schema.yml
> +    A set of API endpoints that allow you to get information about person in Osis app
C'est le schéma qui devait être exposé dans Osis dans le cas ou on récupère pas les données directement via l'ESB ?

2022-11-29 09:38 UTC, basmot commented on formation_metier/static/js/htmx.min.js
> +(function(e,t){if(typeof define==="function"&&define.amd){define([],t)}else{e.htmx=e.htmx||t()}})(typeof self!=="undefined"?self:this,function(){return function(){"use strict";var U={onLoad:t,process
Tu utilises htmx finalement dans tes templates ? Il ne me semble pas en avoir vu ? Tu peux inclure que les librairies qui sont effectivement utilisées dans le projet (on évite en général de push du code, des librairires... qui "seront pour plus tard").

2022-11-29 09:38 UTC, basmot commented on formation_metier/tasks.py
> +    print("passé dans creation de person")
print à retirer

2022-11-29 09:38 UTC, basmot commented on formation_metier/tasks.py
> +    else:
Tu peux ajouter une description dans les exceptions lancées ; cela permet d'être plus compréhensible dans la stacktrace (ou bien, construire tes propres exception "AucunResultatTrouveException", "TypeRenvoyeApiNonGereException", dans ce cas le nom de l'exception se suffit à elle-même - pas besoin de description).

2022-11-29 09:38 UTC, basmot commented on formation_metier/templates/formation_metier/list_formation.html
> +        });
Pourquoi ?

2022-11-29 09:38 UTC, basmot commented on formation_metier/templatetags/public_cible_display.py
> +    return session.get_public_cible_display()
Dans le template, tu peux directement faire `session|get_public_cible_display` sans passer par un templatetag

2022-11-29 09:38 UTC, basmot commented on formation_metier/tests/form/test_new_formation_form.py
> +    def test_get_without_force_login(self):
Par convention dans Osis, nous nommons nos tests selon ce qu'ils "devraient faire" et donc on les nomme comme suit : `test_should_<faire qqch>`.
Exemple : test_should_deny_access, test_should_autorise_access_to_<role_XXX>, ...

2022-11-29 09:38 UTC, basmot commented on formation_metier/tests/form/test_new_formation_form.py
> +        # self.assertFormError(request, 'form', "name", ["Un objet Formation avec ce champ Code existe déjà."])
Du coup je pense non pertinent - à supprimer ?

2022-11-29 09:38 UTC, basmot commented on formation_metier/tests/form/test_new_formation_form.py
> +    def test_with_invalid_data_code_length(self):
Autre exemple pour ici, je renommerais : test_should_validate_formation_code_length
Les tests devraient refléter plus le métier que des "validations techniques"

2022-11-29 09:38 UTC, basmot commented on formation_metier/tests/form/test_new_formation_form.py
> +        response = self.client.get(URL_NEW_FORMATION_VIEW)
Du coup à supprimer ?

2022-11-29 09:38 UTC, basmot commented on formation_metier/tests/form/test_new_register_form.py
> +        cls.participant6 = create_test_participant(person=cls.person7)
Tu peux utiliser FactoryBoy pour créer des jeux de tests pour tes données, regarde qqs exemples dans Osis (tests/factory)

2022-11-29 09:38 UTC, basmot commented on formation_metier/tests/form/test_new_register_form.py
> +        cls.register4 = create_test_register(session=cls.session1, participant=cls.participant4)
Quand un SetUp d'un test devient kilométrique, c'est indateur qu'il fait trop de choses (et deviendra très difficilement maintenable). Questions :
- as-tu besoin d'autant de cas différents pour tes tests ?
- est-ce que toutes ces données du setUp sont partagées par tous tes tests ?

Le setUp ne reprend que les éléments communs/transversaux à tous les tests ; si besoin d'un cas particulier, il vaut mieux le créer à l'intérieur du test par facilité de comprhénesion.

2022-11-29 09:38 UTC, basmot commented on formation_metier/views/delete_formation_view.py
> +    return redirect('formation_metier:list_formation')
Raison particulière pour utiliser une function based view plutot que class based view ?

2022-11-29 09:38 UTC, basmot commented on module_formation/.env
> +ROLES_OSIS='['CentralManagerEducationGroup','FacultyManagerEducationGroup','ContinuingEducationTrainingManager','ContinuingEducationStudentWorker','ContinuingEducationManager','PartnershipEntityManag
Encore pertinent ?

2022-11-29 12:30 UTC, vbrichant commented on formation_metier/exemple_data_from_api.py
> +     }
C'était déjà l'indentation automatique de PyCharm,

2022-11-29 13:10 UTC, vbrichant commented on formation_metier/templatetags/public_cible_display.py
> +    return session.get_public_cible_display()
C'était suite à une discussion avec toi ou Benjamin concernant l'affichage de cette enums, on m'avais dis de faire un templateTag car c'était un bon exercise

2022-11-29 13:12 UTC, vbrichant commented on formation_metier/views/detail_session.py
> +            return HttpResponseForbidden()
En effet c'est un morcaux de code qui reste du moment où je n'avais pas encore fait les permissions

2022-11-29 13:40 UTC, vbrichant commented on formation_metier/static/js/htmx.min.js
> +(function(e,t){if(typeof define==="function"&&define.amd){define([],t)}else{e.htmx=e.htmx||t()}})(typeof self!=="undefined"?self:this,function(){return function(){"use strict";var U={onLoad:t,process
Si je l'utilise dans des modals que j'utilise pour les suppression de formation,seance et registration
Ce ficher est encore un oubli étant donné que j'ai django-htmx dans mon requirement.txt

2022-11-29 13:43 UTC, vbrichant commented on formation_metier/api/serializers/person.py
> +        fields = ['id', 'name', 'numberFGS', 'role_formation_metier']
Suite a la dernière réunion, je compte en effet faire la traduction de mon code en FR

2022-11-29 16:01 UTC, vbrichant commented on formation_metier/schema.yml
> +    A set of API endpoints that allow you to get information about person in Osis app
Non c'est un schéma que j'avais généré lorsque j'ai crée une API sur mon module. Cette API de test ne renvois que des données de mon propre module et est appelé de mon module. Elle ne m'a servis que pour comprendre les API

2022-11-29 16:06 UTC, vbrichant commented on formation_metier/migrations/0033_alter_person_options.py
> +    ]
Via quel mécanisme ? La commande 'squashmigrations' ou bien en recréant artificiellement une migration unique (comme si on ne fesait qu'une seule fois 'migrate' lorsque tous modèles sont définitif)

2022-11-30 07:38 UTC, vbrichant commented on formation_metier/views/detail_session.py
> +            register.save()
Je m'y suis peut-être mal pris mais non quand j'ai implémenté ce formulaire j'ai été obligé de faire comme ça pour que ça marche (vu que je n'y arrivais pas, Benjamin l'a fait avec moi)

2022-12-02 13:18 UTC, vbrichant commented on formation_metier/views/delete_formation_view.py
> +    return redirect('formation_metier:list_formation')
Non il n'y a pas de raison particulière ici

2022-12-02 13:22 UTC, vbrichant commented on formation_metier/views/delete_session_view.py
> +    return redirect('formation_metier:detail_formation', session.formation.id)
Ici il y a une raison, vu que il faut supprimer plusieurs Register, je n'ai rien trouvé qui me permette de le faire un suppression de plusieur object dans une class based view et donc je suis partis sur une function based view

2022-12-05 16:01 UTC, vbrichant commented on formation_metier/views/detail_session.py
> +            register.save()
étant donné que dans les donnée du formulaire je n'ai pas 'session'(actuellement seance) et que la vue detail_seance est composé d'une DetailView et d'une FormView, c'est le seul moyen que j'ai trouvé pour pouvoir correctement créer mon object Register

2022-12-05 16:04 UTC, vbrichant commented on formation_metier/api/urls_api.py
> +    path('person/<int:pk>/', views.PersonDetail.as_view()),
Les id auto-généré par Django ont été remplacé par des Uuid

2022-12-14 14:42 UTC, basmot commented on formation_metier/migrations/0033_alter_person_options.py
> +    ]
Quand ce sont des nouveaux fichiers pas encore mergés / exécutés en dev (donc existant uniquement dans une PR), tu peux les supprimer manuellement et refaire un makemigrations.

2022-12-14 15:16 UTC, basmot commented on formation_metier/static/js/htmx.min.js
> +(function(e,t){if(typeof define==="function"&&define.amd){define([],t)}else{e.htmx=e.htmx||t()}})(typeof self!=="undefined"?self:this,function(){return function(){"use strict";var U={onLoad:t,process
Django_htmx est différent de htmx ; htmx est un outil front end écrit en JS qui permet de faire de l'ajax sans écrire de JS (via des attributs dans les tags html). django-htmx permet de manager les requêtes htmx dans une view Django. Il ne me semble pas avoir vu du code relatif à cela ?

2022-12-14 15:16 UTC, basmot reviewed
+ https://github.com/uclouvain/formation-metier/pull/23#discussion_r1048556450
+ https://github.com/uclouvain/formation-metier/pull/23#discussion_r1048598801

2022-12-14 15:24 UTC, basmot requested changes

2022-12-14 15:24 UTC, basmot commented on requirements.txt
> +zipp==3.10.0
Petite question ; toutes ces librairies sont bien utilisées / utiles ?

2022-12-14 15:24 UTC, basmot commented on formation_metier/tasks.py
> +                name = str(employe_ucl["firstname"]) + " " + str(employe_ucl["lastname"])
Tu peux utiliser les fstrings python

2022-12-14 15:24 UTC, basmot commented on formation_metier/tests/form/test_nouvelle_formation_form.py
> +class NouvelleFormationFormTest(TestCase):
Je vois ça maintenant, enfait les tests cidessous sont bien des tests d'une view plus que d'un formulaire ; tu peux donc intégrer ces tests ci-dessous direcetmetn dans tes ficheirs de tests des views (et derrière, ça teste effectivement tes forms, mais les assertions sont basées sur des codes HTTP et request body, c'est donc indépendent des forms - tu pourrais refactorer ton code pour utiliser autre chose que tes forms comme par exemple du DDD, ça fonctionnerait aussi).

2022-12-15 09:52 UTC, vbrichant commented on requirements.txt
> +zipp==3.10.0
Je pense qu'elles sont toutes utilisée dans le projet. Mais après réflexion, j'ai réduit requerement.txt étant donné que beaucoup sont des dépendances et donc il n'y a pas de vraiment sens à ce qu'elles soient présentes

2022-12-15 10:13 UTC, vbrichant commented on formation_metier/migrations/0033_alter_person_options.py
> +    ]
Ok je comprend le mécanisme, je mettrais ça en place dans les prochaines PR

2022-12-15 10:17 UTC, vbrichant commented on formation_metier/static/js/htmx.min.js
> +(function(e,t){if(typeof define==="function"&&define.amd){define([],t)}else{e.htmx=e.htmx||t()}})(typeof self!=="undefined"?self:this,function(){return function(){"use strict";var U={onLoad:t,process
En effet, je n'utilisait pas django_htmx, j'avais cru naïvement que django_htmx était juste une version de HTMX pour Django

2023-02-14 09:59 UTC, closed without merging