Review 2
uclouvain/formation-metier pull request #49
Opened 2022-12-08 10:48 UTC by vbrichant

Review sur tous les commit depuis la première review

2022-12-16 12:18 UTC, basmot requested changes

2022-12-16 12:18 UTC, basmot commented on formation_metier/views/liste_formation_view.py
> +    template_name = "formation_metier/liste_des_formation.html"
typo liste_des_formation -> liste_des_formations

2022-12-16 12:18 UTC, basmot commented on formation_metier/views/liste_formation_view.py
> +    name = 'liste_formation'
Pourquoi pas uniformiser le nommage ? (soit liste_des_formations soit liste_formations)
- template_name = liste_des_formations.html
- context_object_name = "liste_des_formations"
- name = "liste_des_formations"

à vérifier pour les autres views ?

2022-12-16 12:18 UTC, basmot commented on formation_metier/views/modification_formation_view.py
> +    pk_url_kwarg = "formation_id"
Si tu as des uuids, n'oublie pas de modifier pour l'utiliser dans les views (à vérifier pour les autres views ?)

2022-12-16 12:18 UTC, basmot commented on formation_metier/views/modification_formation_view.py
> +    success_message = 'La formation %(name)s a été modifiée.'
Dans le projet on utilise pas du tout le système de traduction ?

2022-12-16 12:18 UTC, basmot commented on formation_metier/views/selection_participant_widget_view.py
> +        return qs
Attention, avec ce code, si j'envoie un apram de recehrcher vide, la query va charger tout le contenu de la table ; à éviter

2022-12-16 12:18 UTC, basmot commented on formation_metier/views/suppression_inscription_par_formateur_view.py
> +            return redirect('formation_metier:detail_seance', seance_id)
`if request.method == "POST":`  pas nécessaire ?
Je suis pas sur de voir l'intérêt de cette partie du code ?

2022-12-16 12:18 UTC, basmot commented on formation_metier/views/suppression_inscription_par_participant_view.py
> +            )
Le comportement par défaut est pas de renvoyerun 404 si l'objet n'existe pas ? Du coup est-ce que le `AssertionError("Vous n'êtes pas inscrit à cette seance")` est nécessaire ? Et est-ce que c'est nécessaire d'override la fonction delete() ? Juste donner les params 'success_url" et "success_message" sont pas suffisants ?

2022-12-19 09:08 UTC, vbrichant commented on formation_metier/views/modification_formation_view.py
> +    success_message = 'La formation %(name)s a été modifiée.'
Non pour l'instant il n'y a aucun mécanisme de traduction, mais je peut le mettre en place si il le faut pour cette itération

2022-12-19 09:14 UTC, vbrichant commented on formation_metier/views/selection_participant_widget_view.py
> +        return qs
étant donné que j'ai mis au widget ce paramètre :" 'data-minimum-input-length': 3 " ,il me semblais que aucune requête ne serais lancée avant l'entrée de 3 caractères dans l'input (fichier : form/nouvelle_inscription_par_formateur_form.py)

2022-12-19 13:48 UTC, vbrichant commented on formation_metier/views/suppression_inscription_par_participant_view.py
> +            )
Vu que cette vue fait la suppression de plusieurs inscription, je n'ai rien trouvé me permettant de les supprimer sans override delete().
Parce que si j'ai bien compris, la DeleteView se base sur la DeletionMixin pour réaliser le delete sur self.get_object() . Or le self.object ne peux renvoyer qu'un seul object

2022-12-19 13:57 UTC, vbrichant commented on formation_metier/views/suppression_inscription_par_formateur_view.py
> +            return redirect('formation_metier:detail_seance', seance_id)
Le but est de supprimer une ou un certain nombre d'inscription. Le formulaire est constitué de plusieurs checkbox. Chaque checkbox représentant une inscription pour la seance actuelle.
Cette partie de code a pour but de supprimer la liste d'inscription reçue par le formulaire et d'afficher un message pour chaque inscription supprimée

2022-12-20 08:05 UTC, vbrichant commented on formation_metier/views/inscription_seance_pour_participant_view.py
> +        inscription.save()
Le code ne marchais pas sans ce bout de code, mais maintenant le formView a été remplacé par une createView ce qui permet d'éviter ce genre de code car l'object est créé automatiquement par la CreateView

2022-12-20 08:05 UTC, vbrichant commented on formation_metier/views/inscription_seance_pour_participant_view.py
> +        return super().post(self, request, *args, **kwargs)
Je le fesait afin de pouvoir ajouter les valeurs de seance et de participant dans les data du formulaire, étant donné que c'est un formulaire sans champs visible.
Après réflexion, j'ai modifier le code afin de ne plus override le post et d'attribuer les valeurs voulue pour seance et participant lors du get_form_class()

2022-12-20 10:17 UTC, vbrichant commented on formation_metier/views/modification_formation_view.py
> +    pk_url_kwarg = "formation_id"
Je ne suis pas sûr de comprendre, le champ id de tout mes modèles est de type UUID. Donc si je comprend bien, j'utilise déjà les uuid dans toutes les vues basée sur un object

2022-12-20 10:37 UTC, vbrichant commented on formation_metier/views/inscription_formation_pour_participant_view.py
> +                    )
Le formulaire (sans class) est une liste decheckbox chacun correspondant à l'inscription de l'user dans une seance.
Lors de l'initialisation du formulaire certains checkbox sont déjà checked en fonction de si l'user est déjà inscrit à la seance.
L'utilisateur peux donc cocher une seance pour s'inscrire ou dé-cocher une séance pour se désinscrire. 
Dans le code : premièrement on supprime les inscription correspondant au séance qui on été décochée (1er FOR) et on ajoute ensuite une inscription par séance qui a été cochée dans le formulaire (2eme FOR)

2023-02-14 10:00 UTC, vbrichant commented
Ancienne PR

2023-02-14 10:00 UTC, closed without merging