Update Queryset du widget Select2
uclouvain/formation-metier pull request #62
Opened 2022-12-16 15:32 UTC by vbrichant

Filtre du queryset afin de ne plus avoir les employé deja inscrit à la seance

2022-12-19 08:18 UTC, basmot requested changes

2022-12-19 08:18 UTC, basmot commented on formation_metier/forms/nouvelle_inscription_par_formateur_form.py
> +        pprint(self.instance)
à supprimer

2022-12-19 08:18 UTC, basmot commented on formation_metier/views/selection_participant_widget_view.py
>  class SelectionParticipantView(LoginRequiredMixin, PermissionRequiredMixin, autocomplete.Select2QuerySetView):
Par convention dans Osis, on suffixe nos views que sont des autocomplete avec `AutoComplete` -> `SelectionParticipantAutoComplete`

2022-12-19 08:18 UTC, basmot commented on formation_metier/views/selection_participant_widget_view.py
> +        qs = EmployeUCLouvain.objects.exclude(name__in=inscription_list)
C'est nécessaire de préfiltrer à l'avance ? Avec la validation qui dit "peut pas inscrire 2 fois à la même séance", c'est pas suffisant ?

2022-12-19 08:43 UTC, vbrichant commented on formation_metier/views/selection_participant_widget_view.py
> +        qs = EmployeUCLouvain.objects.exclude(name__in=inscription_list)
En effet ce n'est pas nécésaire, mais étant donné qu'on évite à l'utilisateur  de faire une erreur cela me semblais pertinant d'ajouter le préfiltrage.
Le coût en performance est t'il a prévilégier par rapport à l'expériance utilisateur ?
PS: je comptais retirer la validation

2022-12-20 16:05 UTC, basmot commented on formation_metier/views/selection_participant_widget_view.py
> +        qs = EmployeUCLouvain.objects.exclude(name__in=inscription_list)
De ce que je comprends, c'est un invariant métier "un utilisatuer ne peut pas s'inscrire 2 fois à une mêmle séance" et donc à laisser dans le code. Ici, la liste des Employe UCLouvain fait 6000 résultats ; est-ce que le fait de retirer les quelques personnes qui y participent déjà améliore vraiment l'expérience utilisateur ?

2022-12-21 07:58 UTC, vbrichant commented on formation_metier/views/selection_participant_widget_view.py
> +        qs = EmployeUCLouvain.objects.exclude(name__in=inscription_list)
C'est vrai que au vu du nombre d'Employé, l'amélioration n'est pas suffisament significative. Je vais supprimer cette fonctionnalitée.

2022-12-21 09:49 UTC, basmot approved these changes

2022-12-21 13:04 UTC, merged