Refactor des DeleteView sur les inscriptions
uclouvain/formation-metier pull request #66
Opened 2022-12-19 14:05 UTC by vbrichant

- SuppressionInscriptionParParticipant : définition de get_success_url et de get_object afin de ne plus overwrite delete()
- SuppressionInscriptionParFormateur : implémentation de get_success_url + modif de delete()

2022-12-20 16:09 UTC, basmot requested changes

2022-12-20 16:09 UTC, basmot commented on formation_metier/views/suppression_inscription_par_participant_view.py
> +            seance__id=self.request.POST.get('seance_id')
Optionnel : pour éviter de faire une jointure, tu peux directement mettre `participant_id` au lieu de `participant__id`, pareil pour `seance_id `

2022-12-21 08:15 UTC, vbrichant commented on formation_metier/views/suppression_inscription_par_participant_view.py
> +            seance__id=self.request.POST.get('seance_id')
C'est modifié, je vais aussi regarder dans le reste du projet si il y a d'autre endroit ou j'ai fait pareil

2022-12-21 09:50 UTC, basmot approved these changes

2022-12-21 13:02 UTC, merged