Refactor inscription formation et seance pour participant
uclouvain/formation-metier pull request #67
Opened 2022-12-20 11:18 UTC by vbrichant

FormVue -> CreateView
Ajout d'un champ seance dans le formulaire
Ajout de valeur initiales pour les champs du formulaire
Rename nom de class pour l'inscription

2022-12-20 16:13 UTC, basmot requested changes

2022-12-20 16:13 UTC, basmot commented on formation_metier/views/inscription_formation_pour_participant_view.py
> +        )
Je pense que tu peux simplifier ce doe en héritant dans ta view de DeleteView et CreateView si je comprends bien le besoin ?

2023-02-09 16:07 UTC, albrugnetti requested changes

2023-02-09 16:07 UTC, albrugnetti commented on formation_metier/views/inscription_formation_pour_participant_view.py
> +            seance_uuid_list_apres_post.append(UUID(seance))
En Python, tu as le concept de 'list comprehension ' qui te permet d'éviter de faire une boucle si tu fais un traitement.

```python
seance_uuid_list_apres_post = [UUID(seance) for seance in seance_list_apres_post]

2023-02-09 16:07 UTC, albrugnetti commented on formation_metier/views/inscription_formation_pour_participant_view.py
> +class InscriptionFormationPourParticipant(LoginRequiredMixin, CreateView, DeleteView, SingleObjectMixin):
Est-ce que les mixin CreateView / DeleteView sont encore pertinentes ?

2023-02-14 10:12 UTC, merged